blank_issues_enabled: true
contact_links:
	- name: Controller mapping
		url: ./../../discussions/13
		about: Share the mapping you got for your controller
	- name: Custom skin
		url: ./../../discussions/14
		about: Share the skin you've made or modified
